name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        
    - name: Setup cache for Bundler
      id: cache
      uses:  actions/cache@v4
      with:
        path: |
           vendor/bundle
        key: ${{ runner.os }}-bundler-${{ hashFiles('docs/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-bundler-

    - name: Install Dependencies
      run: |
        bundle install --jobs=4 --retry=3

    - name: Build Jekyll site
      run: bundle exec jekyll build
      
#    - name: Update Algolia index
#      run: bundle exec jekyll algolia push
#      env:
#        ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
#      continue-on-error: true